project:
  type: website

website:
  title: "Insights from QGreenland workshops"
  navbar:
    left:
      - href: index.qmd
        text: Abstract
      - href: references.md
        text: References

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



